//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class AutoClassMaker
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.ScriptManager smgrORMClass;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgORMCLass;
        protected global::System.Web.UI.WebControls.DropDownList ddlTables;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlClassFileName;
        protected global::System.Web.UI.WebControls.TextBox tbxORMClassFileName;
        protected global::System.Web.UI.WebControls.Button btnGo;

        */
    }
}
