//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class XMLtoSQL
    {
        protected global::System.Web.UI.WebControls.TextBox FileNameTextBox;
        protected global::System.Web.UI.WebControls.Button GoButton;
        protected global::System.Web.UI.WebControls.GridView gvSQLResults;
        protected global::System.Web.UI.WebControls.Panel pnlSQLResults;
    }
}
