//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL
{
    public partial class ManageUsers
    {
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.GridView gvUserAccounts;
    }
}
