//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL
{
    public partial class DisableClient
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmDisable;
        protected global::System.Web.UI.WebControls.Literal ltrlPageHeading;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl confirmationSection;
        protected global::System.Web.UI.WebControls.Literal ltrlConfirmationHeader;
        protected global::System.Web.UI.WebControls.Literal ltrlConfirmationMessage;
        protected global::System.Web.UI.WebControls.Label CompanyNameLabel;
        protected global::System.Web.UI.WebControls.Literal ltrlWarningMessage;
        protected global::System.Web.UI.WebControls.RadioButton rbRemindersOnly;
        protected global::System.Web.UI.WebControls.Label lblRemindersOnly;
        protected global::System.Web.UI.WebControls.Literal ltrlRemindersHelp;
        protected global::System.Web.UI.WebControls.RadioButton rbDisableAll;
        protected global::System.Web.UI.WebControls.Label lblDisableAll;
        protected global::System.Web.UI.WebControls.Literal ltrlAllHelp;
        protected global::System.Web.UI.WebControls.Literal ltrlOptionsHelp;
        protected global::System.Web.UI.WebControls.Button btnConfirmDisable;
        protected global::System.Web.UI.WebControls.Literal ltrlCancelText;
        protected global::System.Web.UI.WebControls.Literal ltrlHelpMessage;
        protected global::System.Web.UI.WebControls.Literal ltrlContactEmail;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl successSection;
        protected global::System.Web.UI.WebControls.Literal ltrlSuccessHeader;
        protected global::System.Web.UI.WebControls.Literal ltrlSuccessMessage;
        protected global::System.Web.UI.WebControls.Label CompanyNameSuccessLabel;
        protected global::System.Web.UI.WebControls.Literal ltrlSuccessDetails;
        protected global::System.Web.UI.WebControls.Literal ltrlReenableMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl errorSection;
        protected global::System.Web.UI.WebControls.Literal ltrlErrorHeader;
        protected global::System.Web.UI.WebControls.Literal ltrlErrorMessage;
        protected global::System.Web.UI.WebControls.Literal ltrlReturnHomeText;
    }
}
