//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class index
    {
        protected global::System.Web.UI.WebControls.Label Label1;
        protected global::System.Web.UI.WebControls.TextBox txtFrom;
        protected global::System.Web.UI.WebControls.Label lblPass;
        protected global::System.Web.UI.WebControls.TextBox txtPass;
        protected global::System.Web.UI.WebControls.Label EmailServer;
        protected global::System.Web.UI.WebControls.TextBox txtMailServer;
        protected global::System.Web.UI.WebControls.Label Label2;
        protected global::System.Web.UI.WebControls.TextBox txtTo;
        protected global::System.Web.UI.WebControls.Button btnSend;
        protected global::System.Web.UI.WebControls.Label lblStatus;
    }
}
