//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackerDotNet.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your away period from {0} to {1} has been recorded.&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        public static string AwayPeriod_ConfirmationBody {
            get {
                return ResourceManager.GetString("AwayPeriod.ConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During this time, please be aware that our system will not send out any reminders. However, coffee will be available for manual ordering, ensuring you can enjoy your favourites whenever you choose..
        /// </summary>
        public static string AwayPeriod_ConfirmationInfo {
            get {
                return ResourceManager.GetString("AwayPeriod.ConfirmationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Period Confirmation for {0}.
        /// </summary>
        public static string AwayPeriod_ConfirmationSubject {
            get {
                return ResourceManager.GetString("AwayPeriod.ConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        public static string AwayPeriod_Greeting {
            get {
                return ResourceManager.GetString("AwayPeriod.Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Dates: Prep {0}, Delivery {1}.
        /// </summary>
        public static string CoffeeCheckup_AdjustedDatesLabel {
            get {
                return ResourceManager.GetString("CoffeeCheckup.AdjustedDatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&apos;color: red; font-weight: bold;&apos;&gt;⚠️ FINAL REMINDER: This is the last automated reminder we&apos;ll send. If you no longer need coffee reminders, please let us know.&lt;/div&gt;&lt;br/&gt;.
        /// </summary>
        public static string CoffeeCheckup_BodyFinalWarning {
            get {
                return ResourceManager.GetString("CoffeeCheckup.BodyFinalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your {0} is ready for processing:&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckup_BodyOrderType {
            get {
                return ResourceManager.GetString("CoffeeCheckup.BodyOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;It&apos;s time for your next coffee order! Based on your previous orders, here&apos;s what we think you might need:&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckup_BodyReminderOnly {
            get {
                return ResourceManager.GetString("CoffeeCheckup.BodyReminderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted for closure date: {0}.
        /// </summary>
        public static string CoffeeCheckup_ClosureAdjustmentPrefix {
            get {
                return ResourceManager.GetString("CoffeeCheckup.ClosureAdjustmentPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Status.
        /// </summary>
        public static string CoffeeCheckup_DialogEmailStatusTitle {
            get {
                return ResourceManager.GetString("CoffeeCheckup.DialogEmailStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Order Date Error.
        /// </summary>
        public static string CoffeeCheckup_DialogRecurringDateTitle {
            get {
                return ResourceManager.GetString("CoffeeCheckup.DialogRecurringDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Table Error.
        /// </summary>
        public static string CoffeeCheckup_DialogTempTableTitle {
            get {
                return ResourceManager.GetString("CoffeeCheckup.DialogTempTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch email sending failed.
        /// </summary>
        public static string CoffeeCheckup_ErrorBatchEmailFailure {
            get {
                return ResourceManager.GetString("CoffeeCheckup.ErrorBatchEmailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send coffee checkup email.
        /// </summary>
        public static string CoffeeCheckup_ErrorEmailSending {
            get {
                return ResourceManager.GetString("CoffeeCheckup.ErrorEmailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create order for customer.
        /// </summary>
        public static string CoffeeCheckup_ErrorOrderInsert {
            get {
                return ResourceManager.GetString("CoffeeCheckup.ErrorOrderInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set recurring order dates.
        /// </summary>
        public static string CoffeeCheckup_ErrorRecurringDateFailure {
            get {
                return ResourceManager.GetString("CoffeeCheckup.ErrorRecurringDateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear temporary checkup tables.
        /// </summary>
        public static string CoffeeCheckup_ErrorTempTableDelete {
            get {
                return ResourceManager.GetString("CoffeeCheckup.ErrorTempTableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert records into temporary tables.
        /// </summary>
        public static string CoffeeCheckup_ErrorTempTableInsert {
            get {
                return ResourceManager.GetString("CoffeeCheckup.ErrorTempTableInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;p&gt;If you would prefer not to receive these reminders, &lt;a href=&apos;{0}&apos;&gt;click here to disable them&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckup_FooterDisableLink {
            get {
                return ResourceManager.GetString("CoffeeCheckup.FooterDisableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;✅ &lt;strong&gt;Good news!&lt;/strong&gt; We&apos;ve automatically created an order for you with the items above.&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckup_FooterOrderAdded {
            get {
                return ResourceManager.GetString("CoffeeCheckup.FooterOrderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;📋 &lt;a href=&apos;{0}&apos;&gt;View your order details here&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckup_FooterOrderLink {
            get {
                return ResourceManager.GetString("CoffeeCheckup.FooterOrderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi Coffee Lover,&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckup_GreetingGeneric {
            get {
                return ResourceManager.GetString("CoffeeCheckup.GreetingGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi {0},&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckup_GreetingWithName {
            get {
                return ResourceManager.GetString("CoffeeCheckup.GreetingWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;Heads-up:&lt;/i&gt; Upcoming holidays or scheduled closures may affect delivery dates..
        /// </summary>
        public static string CoffeeCheckup_HolidayClosureEmailNote {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HolidayClosureEmailNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;padding: 5px 8px; border-bottom: 1px solid #eee; background-color: #f9f9f9;&quot;&gt;{0}&lt;/td&gt;.
        /// </summary>
        public static string CoffeeCheckup_HtmlTableCellAlt {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HtmlTableCellAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;padding: 5px 8px; border-bottom: 1px solid #eee;&quot;&gt;{0}&lt;/td&gt;.
        /// </summary>
        public static string CoffeeCheckup_HtmlTableCellNormal {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HtmlTableCellNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr style=&quot;background-color: #f2f2f2;&quot;&gt;&lt;td colspan=&quot;2&quot; style=&quot;font-weight: bold; padding: 8px; border-bottom: 1px solid #ccc;&quot;&gt;{0}: {1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string CoffeeCheckup_HtmlTableHeader {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HtmlTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Here are the details for your next coffee delivery:&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckup_HtmlTableIntro {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HtmlTableIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&quot;padding: 5px 8px; border-bottom: 1px solid #eee; font-weight: bold; background-color: #f0f0f0; width: 40%;&quot;&gt;{0}&lt;/td&gt;&lt;td style=&quot;padding: 5px 8px; border-bottom: 1px solid #eee;&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string CoffeeCheckup_HtmlTableRowAlt {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HtmlTableRowAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td colspan=&quot;2&quot; style=&quot;padding: 8px; font-weight: bold; background-color: #e6f3ff; border-bottom: 1px solid #ccc;&quot;&gt;{0}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string CoffeeCheckup_HtmlTableRowColspan {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HtmlTableRowColspan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&quot;padding: 5px 8px; border-bottom: 1px solid #eee; font-weight: bold; background-color: #f9f9f9; width: 40%;&quot;&gt;{0}&lt;/td&gt;&lt;td style=&quot;padding: 5px 8px; border-bottom: 1px solid #eee;&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string CoffeeCheckup_HtmlTableRowNormal {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HtmlTableRowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellpadding=&quot;5&quot; cellspacing=&quot;0&quot; style=&quot;border-collapse: collapse; font-family: Arial, sans-serif; margin: 10px 0;&quot;&gt;.
        /// </summary>
        public static string CoffeeCheckup_HtmlTableStart {
            get {
                return ResourceManager.GetString("CoffeeCheckup.HtmlTableStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-fulfill Order.
        /// </summary>
        public static string CoffeeCheckup_OrderTypeAutoFulfill {
            get {
                return ResourceManager.GetString("CoffeeCheckup.OrderTypeAutoFulfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring + Auto-fulfill Order.
        /// </summary>
        public static string CoffeeCheckup_OrderTypeCombined {
            get {
                return ResourceManager.GetString("CoffeeCheckup.OrderTypeCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Order.
        /// </summary>
        public static string CoffeeCheckup_OrderTypeRecurring {
            get {
                return ResourceManager.GetString("CoffeeCheckup.OrderTypeRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Only.
        /// </summary>
        public static string CoffeeCheckup_OrderTypeReminderOnly {
            get {
                return ResourceManager.GetString("CoffeeCheckup.OrderTypeReminderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some reminder emails failed to send.
        /// </summary>
        public static string CoffeeCheckup_StatusBatchSendPartial {
            get {
                return ResourceManager.GetString("CoffeeCheckup.StatusBatchSendPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All reminder emails sent successfully.
        /// </summary>
        public static string CoffeeCheckup_StatusBatchSendSuccess {
            get {
                return ResourceManager.GetString("CoffeeCheckup.StatusBatchSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee checkup reminders processed successfully.
        /// </summary>
        public static string CoffeeCheckup_StatusRemindersProcessed {
            get {
                return ResourceManager.GetString("CoffeeCheckup.StatusRemindersProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-fulfill Coffee Order Created.
        /// </summary>
        public static string CoffeeCheckup_SubjectAutoFulfill {
            get {
                return ResourceManager.GetString("CoffeeCheckup.SubjectAutoFulfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Order Ready - Recurring &amp; Auto-fulfill Items.
        /// </summary>
        public static string CoffeeCheckup_SubjectCombined {
            get {
                return ResourceManager.GetString("CoffeeCheckup.SubjectCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Coffee Order Ready.
        /// </summary>
        public static string CoffeeCheckup_SubjectRecurring {
            get {
                return ResourceManager.GetString("CoffeeCheckup.SubjectRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Reminder - Time for Your Next Order.
        /// </summary>
        public static string CoffeeCheckup_SubjectReminderOnly {
            get {
                return ResourceManager.GetString("CoffeeCheckup.SubjectReminderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/Contact.
        /// </summary>
        public static string CoffeeCheckup_TableCompanyContact {
            get {
                return ResourceManager.GetString("CoffeeCheckup.TableCompanyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Items.
        /// </summary>
        public static string CoffeeCheckup_TableListOfItems {
            get {
                return ResourceManager.GetString("CoffeeCheckup.TableListOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next estimate dispatch date.
        /// </summary>
        public static string CoffeeCheckup_TableNextDispatchDate {
            get {
                return ResourceManager.GetString("CoffeeCheckup.TableNextDispatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next estimate prep date.
        /// </summary>
        public static string CoffeeCheckup_TableNextPrepDate {
            get {
                return ResourceManager.GetString("CoffeeCheckup.TableNextPrepDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CoffeeCheckup_TableType {
            get {
                return ResourceManager.GetString("CoffeeCheckup.TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming closure date(s): {0}.
        /// </summary>
        public static string CoffeeCheckup_UpcomingClosures {
            get {
                return ResourceManager.GetString("CoffeeCheckup.UpcomingClosures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again..
        /// </summary>
        public static string Common_ErrorGeneric {
            get {
                return ResourceManager.GetString("Common.ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string Common_SuccessGeneric {
            get {
                return ResourceManager.GetString("Common.SuccessGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} (ID: {1}) disabled successfully.
        /// </summary>
        public static string Customer_Disabled {
            get {
                return ResourceManager.GetString("Customer.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} (ID: {1}) disabled via self-service.
        /// </summary>
        public static string Customer_DisabledViaSelfService {
            get {
                return ResourceManager.GetString("Customer.DisabledViaSelfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disabling customer {0}: {1}.
        /// </summary>
        public static string Customer_DisableError {
            get {
                return ResourceManager.GetString("Customer.DisableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment updated for customer {0}: Type {1}, SN {2}.
        /// </summary>
        public static string Customer_EquipmentUpdated {
            get {
                return ResourceManager.GetString("Customer.EquipmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment update failed for customer {0}: {1}.
        /// </summary>
        public static string Customer_EquipmentUpdateError {
            get {
                return ResourceManager.GetString("Customer.EquipmentUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} not found.
        /// </summary>
        public static string Customer_NotFound {
            get {
                return ResourceManager.GetString("Customer.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder count reset for customer {0}, force enable: {1}.
        /// </summary>
        public static string Customer_ReminderCountReset {
            get {
                return ResourceManager.GetString("Customer.ReminderCountReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated optimal dates for {0} - Target day {1}: Roast {2}, Delivery {3}.
        /// </summary>
        public static string DeliveryCalculation_CalculatedOptimalDates {
            get {
                return ResourceManager.GetString("DeliveryCalculation.CalculatedOptimalDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating monthly delivery for customer {0}, target day {1}.
        /// </summary>
        public static string DeliveryCalculation_CalculatingMonthlyDelivery {
            get {
                return ResourceManager.GetString("DeliveryCalculation.CalculatingMonthlyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating weekly delivery for customer {0}, every {1} weeks.
        /// </summary>
        public static string DeliveryCalculation_CalculatingWeeklyDelivery {
            get {
                return ResourceManager.GetString("DeliveryCalculation.CalculatingWeeklyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0}: Proposed date {1} is in the past.
        /// </summary>
        public static string DeliveryCalculation_DateInPast {
            get {
                return ResourceManager.GetString("DeliveryCalculation.DateInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0}: Proposed date {1} is too far in the future.
        /// </summary>
        public static string DeliveryCalculation_DateTooFarFuture {
            get {
                return ResourceManager.GetString("DeliveryCalculation.DateTooFarFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating delivery date for customer {0}: {1}.
        /// </summary>
        public static string DeliveryCalculation_ErrorCalculatingDelivery {
            get {
                return ResourceManager.GetString("DeliveryCalculation.ErrorCalculatingDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating monthly occurrence for day {0}: {1}.
        /// </summary>
        public static string DeliveryCalculation_ErrorCalculatingOccurrence {
            get {
                return ResourceManager.GetString("DeliveryCalculation.ErrorCalculatingOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating roast date from delivery {0}: {1}.
        /// </summary>
        public static string DeliveryCalculation_ErrorCalculatingRoastDate {
            get {
                return ResourceManager.GetString("DeliveryCalculation.ErrorCalculatingRoastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating weekly delivery for customer {0}: {1}.
        /// </summary>
        public static string DeliveryCalculation_ErrorCalculatingWeekly {
            get {
                return ResourceManager.GetString("DeliveryCalculation.ErrorCalculatingWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding city delivery date for customer {0}: {1}.
        /// </summary>
        public static string DeliveryCalculation_ErrorFindingCityDate {
            get {
                return ResourceManager.GetString("DeliveryCalculation.ErrorFindingCityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding closest delivery date: {0}.
        /// </summary>
        public static string DeliveryCalculation_ErrorFindingClosestDate {
            get {
                return ResourceManager.GetString("DeliveryCalculation.ErrorFindingClosestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating delivery date for customer {0}: {1}.
        /// </summary>
        public static string DeliveryCalculation_ErrorValidatingDate {
            get {
                return ResourceManager.GetString("DeliveryCalculation.ErrorValidatingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found next delivery cycle {0} after {1} days.
        /// </summary>
        public static string DeliveryCalculation_FoundNextDeliveryCycle {
            get {
                return ResourceManager.GetString("DeliveryCalculation.FoundNextDeliveryCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid roast date for customer {0}, using target date.
        /// </summary>
        public static string DeliveryCalculation_InvalidRoastDate {
            get {
                return ResourceManager.GetString("DeliveryCalculation.InvalidRoastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next monthly occurrence for day {0}: {1}.
        /// </summary>
        public static string DeliveryCalculation_NextOccurrenceCalculated {
            get {
                return ResourceManager.GetString("DeliveryCalculation.NextOccurrenceCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City roast date {0}, optimal delivery {1}.
        /// </summary>
        public static string DeliveryCalculation_OptimalCityDateFound {
            get {
                return ResourceManager.GetString("DeliveryCalculation.OptimalCityDateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target date {0}, optimal delivery {1}.
        /// </summary>
        public static string DeliveryCalculation_OptimalDateCalculated {
            get {
                return ResourceManager.GetString("DeliveryCalculation.OptimalDateCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery {0}, calculated roast date {1}.
        /// </summary>
        public static string DeliveryCalculation_RoastDateCalculated {
            get {
                return ResourceManager.GetString("DeliveryCalculation.RoastDateCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using city delivery date {0} ({1} days from target).
        /// </summary>
        public static string DeliveryCalculation_UsingCityDeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryCalculation.UsingCityDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using fallback target date {0}.
        /// </summary>
        public static string DeliveryCalculation_UsingFallbackDate {
            get {
                return ResourceManager.GetString("DeliveryCalculation.UsingFallbackDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly target {0}, optimal delivery {1}.
        /// </summary>
        public static string DeliveryCalculation_WeeklyDateCalculated {
            get {
                return ResourceManager.GetString("DeliveryCalculation.WeeklyDateCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has disabled coffee checkup reminders:
        ///
        ///Customer ID: {0}
        ///Company Name: {1}
        ///Disabled Date: {2}
        ///Method: Self-service via email link
        ///
        ///.
        /// </summary>
        public static string DisableClient_AdminBodyHeader {
            get {
                return ResourceManager.GetString("DisableClient.AdminBodyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A goodbye email has been sent to the customer.
        ///
        ///No further action required unless customer contacts you directly..
        /// </summary>
        public static string DisableClient_AdminFooter {
            get {
                return ResourceManager.GetString("DisableClient.AdminFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///⚠️ MANUAL ACTION REQUIRED: Some recurring orders failed to disable automatically.
        ///Please check and disable them manually in the system.
        ///
        ///.
        /// </summary>
        public static string DisableClient_AdminManualActionRequired {
            get {
                return ResourceManager.GetString("DisableClient.AdminManualActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ RECURRING ORDERS FOUND:
        ///- Total recurring orders: {0}
        ///- Successfully disabled: {1}
        ///- Failed to disable: {2}
        ///
        ///Disabled recurring orders:
        ///.
        /// </summary>
        public static string DisableClient_AdminRecurringFound {
            get {
                return ResourceManager.GetString("DisableClient.AdminRecurringFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ No recurring orders found for this customer.
        ///
        ///.
        /// </summary>
        public static string DisableClient_AdminRecurringNone {
            get {
                return ResourceManager.GetString("DisableClient.AdminRecurringNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Disabled Coffee Checkup Reminders - {0}.
        /// </summary>
        public static string DisableClient_AdminSubjectTemplate {
            get {
                return ResourceManager.GetString("DisableClient.AdminSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel &amp; Keep Reminders.
        /// </summary>
        public static string DisableClient_ButtonCancel {
            get {
                return ResourceManager.GetString("DisableClient.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Disable Reminders.
        /// </summary>
        public static string DisableClient_ButtonConfirm {
            get {
                return ResourceManager.GetString("DisableClient.ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📧 Disable Coffee Checkup Reminders?.
        /// </summary>
        public static string DisableClient_ConfirmationHeader {
            get {
                return ResourceManager.GetString("DisableClient.ConfirmationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to disable coffee checkup reminders for:.
        /// </summary>
        public static string DisableClient_ConfirmationMessage {
            get {
                return ResourceManager.GetString("DisableClient.ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We&apos;ve successfully disabled coffee checkup reminders for &lt;strong&gt;{0}&lt;/strong&gt; as requested.&lt;/p&gt;.
        /// </summary>
        public static string DisableClient_DisabledMessage {
            get {
                return ResourceManager.GetString("DisableClient.DisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found. Please contact us for assistance..
        /// </summary>
        public static string DisableClient_ErrorCustomerNotFound {
            get {
                return ResourceManager.GetString("DisableClient.ErrorCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request. Please try again or contact us for assistance..
        /// </summary>
        public static string DisableClient_ErrorGeneral {
            get {
                return ResourceManager.GetString("DisableClient.ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Error.
        /// </summary>
        public static string DisableClient_ErrorHeader {
            get {
                return ResourceManager.GetString("DisableClient.ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing parameters. Please use the link from your email..
        /// </summary>
        public static string DisableClient_ErrorInvalidParams {
            get {
                return ResourceManager.GetString("DisableClient.ErrorInvalidParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired security token. Please use the latest link from your email..
        /// </summary>
        public static string DisableClient_ErrorInvalidToken {
            get {
                return ResourceManager.GetString("DisableClient.ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Visit us: &lt;a href=&apos;http://www.quaffee.co.za&apos; style=&apos;color: #2c5530;&apos;&gt;www.quaffee.co.za&lt;/a&gt;&lt;/p&gt;&lt;p style=&apos;font-size: 12px; color: #666;&apos;&gt;Quaffee Coffee Roastery&lt;br/&gt;Bringing you exceptional coffee since 2008&lt;/p&gt;&lt;/div&gt;.
        /// </summary>
        public static string DisableClient_GoodbyeFooter {
            get {
                return ResourceManager.GetString("DisableClient.GoodbyeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&apos;color: #2c5530;&apos;&gt;Coffee Checkup Reminders Disabled&lt;/h2&gt;.
        /// </summary>
        public static string DisableClient_GoodbyeHeader {
            get {
                return ResourceManager.GetString("DisableClient.GoodbyeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&apos;background-color: #F9FFDF; padding: 20px; border-radius: 8px; margin: 20px 0;&apos;&gt;&lt;p&gt;Hi there,&lt;/p&gt;&lt;p&gt;We&apos;ve successfully disabled coffee checkup reminders for &lt;strong&gt;{0}&lt;/strong&gt; as you requested.&lt;/p&gt;.
        /// </summary>
        public static string DisableClient_GoodbyeMessage {
            get {
                return ResourceManager.GetString("DisableClient.GoodbyeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;🔄 &lt;strong&gt;Want to re-enable reminders?&lt;/strong&gt;&lt;br/&gt;Simply contact us at &lt;a href=&apos;mailto:{0}&apos;&gt;{0}&lt;/a&gt; and we&apos;ll be happy to turn them back on for you.&lt;/p&gt;.
        /// </summary>
        public static string DisableClient_GoodbyeReenableInstructions {
            get {
                return ResourceManager.GetString("DisableClient.GoodbyeReenableInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;☕ &lt;strong&gt;Still need great coffee?&lt;/strong&gt;&lt;br/&gt;Don&apos;t hesitate to reach out! We&apos;re always here to help with your coffee needs.&lt;/p&gt;&lt;/div&gt;.
        /// </summary>
        public static string DisableClient_GoodbyeStillNeedCoffee {
            get {
                return ResourceManager.GetString("DisableClient.GoodbyeStillNeedCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Checkup Reminders Disabled - We&apos;ll Miss You!.
        /// </summary>
        public static string DisableClient_GoodbyeSubject {
            get {
                return ResourceManager.GetString("DisableClient.GoodbyeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&apos;text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;&apos;&gt;&lt;p&gt;&lt;strong&gt;Thank you for being part of the Quaffee family!&lt;/strong&gt;&lt;/p&gt;.
        /// </summary>
        public static string DisableClient_GoodbyeThankYou {
            get {
                return ResourceManager.GetString("DisableClient.GoodbyeThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;📧 &lt;strong&gt;What this means:&lt;/strong&gt;&lt;/p&gt;&lt;ul&gt;&lt;li&gt;You will no longer receive automated coffee checkup reminder emails&lt;/li&gt;&lt;li&gt;Your account remains active for manual orders&lt;/li&gt;&lt;li&gt;You can still contact us anytime for coffee orders&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string DisableClient_GoodbyeWhatThisMeans {
            get {
                return ResourceManager.GetString("DisableClient.GoodbyeWhatThisMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi {0},&lt;/p&gt;.
        /// </summary>
        public static string DisableClient_Greeting {
            get {
                return ResourceManager.GetString("DisableClient.Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 &lt;strong&gt;Need help instead?&lt;/strong&gt;&lt;br /&gt;Contact us at.
        /// </summary>
        public static string DisableClient_HelpMessage {
            get {
                return ResourceManager.GetString("DisableClient.HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Coffee Checkup Reminders - Quaffee.
        /// </summary>
        public static string DisableClient_PageTitle {
            get {
                return ResourceManager.GetString("DisableClient.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Need to re-enable reminders?&lt;/strong&gt;&lt;br /&gt;Contact us at {0} and we&apos;ll be happy to help..
        /// </summary>
        public static string DisableClient_ReenableMessage {
            get {
                return ResourceManager.GetString("DisableClient.ReenableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our administrator has been notified of this change.&lt;br /&gt;You will no longer receive automated coffee checkup reminder emails..
        /// </summary>
        public static string DisableClient_SuccessDetails {
            get {
                return ResourceManager.GetString("DisableClient.SuccessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Reminders Disabled Successfully.
        /// </summary>
        public static string DisableClient_SuccessHeader {
            get {
                return ResourceManager.GetString("DisableClient.SuccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee checkup reminders have been disabled for:.
        /// </summary>
        public static string DisableClient_SuccessMessage {
            get {
                return ResourceManager.GetString("DisableClient.SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ &lt;strong&gt;This will stop all future coffee checkup reminder emails.&lt;/strong&gt;&lt;br /&gt;You can always re-enable reminders by contacting us directly..
        /// </summary>
        public static string DisableClient_WarningMessage {
            get {
                return ResourceManager.GetString("DisableClient.WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email sent successfully.
        /// </summary>
        public static string Email_ConfirmationSent {
            get {
                return ResourceManager.GetString("Email.ConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        public static string Email_ConfirmationSubject {
            get {
                return ResourceManager.GetString("Email.ConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Valued Customer,.
        /// </summary>
        public static string Email_DefaultGreeting {
            get {
                return ResourceManager.GetString("Email.DefaultGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Lover.
        /// </summary>
        public static string Email_DefaultRecipient {
            get {
                return ResourceManager.GetString("Email.DefaultRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},.
        /// </summary>
        public static string Email_GreetingFormat {
            get {
                return ResourceManager.GetString("Email.GreetingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string Email_InvalidAddress {
            get {
                return ResourceManager.GetString("Email.InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification: {0}.
        /// </summary>
        public static string Email_NotificationFormat {
            get {
                return ResourceManager.GetString("Email.NotificationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid email recipient found.
        /// </summary>
        public static string Email_NoValidRecipient {
            get {
                return ResourceManager.GetString("Email.NoValidRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email to {0}: {1}.
        /// </summary>
        public static string Email_SendError {
            get {
                return ResourceManager.GetString("Email.SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;Kind regards,&lt;br/&gt;&lt;br/&gt;&lt;b&gt;The Quaffee Team&lt;/b&gt;&lt;br/&gt;📧 &lt;a href=&apos;mailto:orders@quaffee.co.za&apos;&gt;orders@quaffee.co.za&lt;/a&gt;&lt;br/&gt;🌐 &lt;a href=&apos;http://www.quaffee.co.za&apos;&gt;www.quaffee.co.za&lt;/a&gt;&lt;br/&gt;.
        /// </summary>
        public static string Email_SignatureNoUser {
            get {
                return ResourceManager.GetString("Email.SignatureNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;Kind regards,&lt;br/&gt;&lt;br/&gt;{0}, &lt;b&gt;a member of the Quaffee Team&lt;/b&gt;&lt;br/&gt;📧 &lt;a href=&apos;mailto:orders@quaffee.co.za&apos;&gt;orders@quaffee.co.za&lt;/a&gt;&lt;br/&gt;🌐 &lt;a href=&apos;http://www.quaffee.co.za&apos;&gt;www.quaffee.co.za&lt;/a&gt;&lt;br/&gt;.
        /// </summary>
        public static string Email_SignatureTemplate {
            get {
                return ResourceManager.GetString("Email.SignatureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your business!.
        /// </summary>
        public static string Email_ThankYouMessage {
            get {
                return ResourceManager.GetString("Email.ThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order cancelled.
        /// </summary>
        public static string Order_Cancelled {
            get {
                return ResourceManager.GetString("Order.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order completion failed.
        /// </summary>
        public static string Order_CompletedFailed {
            get {
                return ResourceManager.GetString("Order.CompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order completed successfully.
        /// </summary>
        public static string Order_CompletedSuccess {
            get {
                return ResourceManager.GetString("Order.CompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Completed.
        /// </summary>
        public static string Order_CompletedTitle {
            get {
                return ResourceManager.GetString("Order.CompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;We currently expect your order to be delivered/dispatched on: {0}..
        /// </summary>
        public static string Order_ConfirmationDeliveryDate {
            get {
                return ResourceManager.GetString("Order.ConfirmationDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;This email was sent automatically by Quaffee&apos;s order and tracking System.&lt;br /&gt;.
        /// </summary>
        public static string Order_ConfirmationFooter {
            get {
                return ResourceManager.GetString("Order.ConfirmationFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We confirm the following order:&lt;br /&gt;.
        /// </summary>
        public static string Order_ConfirmationHeader {
            get {
                return ResourceManager.GetString("Order.ConfirmationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}&lt;br /&gt;&lt;p&gt;Thank you for ordering from Quaffee. &lt;/p&gt;.
        /// </summary>
        public static string Order_ConfirmationIntro {
            get {
                return ResourceManager.GetString("Order.ConfirmationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have associated the Purchase Order {0} with this order..
        /// </summary>
        public static string Order_ConfirmationPOReceived {
            get {
                return ResourceManager.GetString("Order.ConfirmationPOReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are awaiting a Purchase order to supply the items, please can you send one through..
        /// </summary>
        public static string Order_ConfirmationPORequired {
            get {
                return ResourceManager.GetString("Order.ConfirmationPORequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely from the Quaffee Team ({0}) ({1}).
        /// </summary>
        public static string Order_ConfirmationSignoff {
            get {
                return ResourceManager.GetString("Order.ConfirmationSignoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaffee Order Confirmation.
        /// </summary>
        public static string Order_ConfirmationSubject {
            get {
                return ResourceManager.GetString("Order.ConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order confirmed successfully.
        /// </summary>
        public static string Order_Confirmed {
            get {
                return ResourceManager.GetString("Order.Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for choosing Quaffee!&lt;br /&gt;.
        /// </summary>
        public static string Order_EmailFooter {
            get {
                return ResourceManager.GetString("Order.EmailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order is scheduled for future processing.
        /// </summary>
        public static string Order_FutureMessage {
            get {
                return ResourceManager.GetString("Order.FutureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Item: {0} — Qty: {1}&lt;/li&gt;.
        /// </summary>
        public static string Order_ItemFormatBasic {
            get {
                return ResourceManager.GetString("Order.ItemFormatBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt; Item: {0} — Qty:  {1} ({2})&lt;/li&gt;.
        /// </summary>
        public static string Order_ItemFormatWithPrep {
            get {
                return ResourceManager.GetString("Order.ItemFormatWithPrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No temporary order found.
        /// </summary>
        public static string Order_NoTempOrderFound {
            get {
                return ResourceManager.GetString("Order.NoTempOrderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found.
        /// </summary>
        public static string Order_NotFound {
            get {
                return ResourceManager.GetString("Order.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order shipped.
        /// </summary>
        public static string Order_Shipped {
            get {
                return ResourceManager.GetString("Order.Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;&lt;br /&gt;Just a quick note to notify you that your Quaffee order has been {1}.&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        public static string Order_StatusBody {
            get {
                return ResourceManager.GetString("Order.StatusBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collected.
        /// </summary>
        public static string Order_StatusCollected {
            get {
                return ResourceManager.GetString("Order.StatusCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valued Customer.
        /// </summary>
        public static string Order_StatusDefaultContact {
            get {
                return ResourceManager.GetString("Order.StatusDefaultContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivered.
        /// </summary>
        public static string Order_StatusDelivered {
            get {
                return ResourceManager.GetString("Order.StatusDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dispatched.
        /// </summary>
        public static string Order_StatusDispatched {
            get {
                return ResourceManager.GetString("Order.StatusDispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your business!.
        /// </summary>
        public static string Order_StatusFooter {
            get {
                return ResourceManager.GetString("Order.StatusFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placed in your postbox.
        /// </summary>
        public static string Order_StatusPostbox {
            get {
                return ResourceManager.GetString("Order.StatusPostbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status Update.
        /// </summary>
        public static string Order_StatusSubject {
            get {
                return ResourceManager.GetString("Order.StatusSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View-only link..
        /// </summary>
        public static string OrderDetail_PublicViewLoginPrompt {
            get {
                return ResourceManager.GetString("OrderDetail.PublicViewLoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Changes.
        /// </summary>
        public static string OrderDetail_RequestChangesButtonText {
            get {
                return ResourceManager.GetString("OrderDetail.RequestChangesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please describe the change you would like to request below this line:\r\n\r\nCustomerID: {0}\r\nDeliveryDate: {1}\r\nRequested change: .
        /// </summary>
        public static string OrderDetail_RequestChangesMailBody {
            get {
                return ResourceManager.GetString("OrderDetail.RequestChangesMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order change request - Customer {0} - Delivery {1}.
        /// </summary>
        public static string OrderDetail_RequestChangesMailSubject {
            get {
                return ResourceManager.GetString("OrderDetail.RequestChangesMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: you&apos;re receiving this because your email is linked to a machine repair.&lt;br /&gt;&lt;br /&gt;
        ///Just a heads-up: Quaffee doesn’t run its own workshop. We help by coordinating with external partners, offering swap-out units when we can, and charging a workshop fee plus a small admin cost.&lt;br /&gt;&lt;br /&gt;
        ///If you&apos;re not a regular coffee client, extra fees for delivery or swap-outs may apply (case-by-case).&lt;br /&gt;&lt;br /&gt;
        ///&lt;p&gt;Warranty is handled directly by the workshop, not by Quaffee.&lt;/p&gt;.
        /// </summary>
        public static string Repairs_DisclaimerFooter {
            get {
                return ResourceManager.GetString("Repairs.DisclaimerFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating repair status.
        /// </summary>
        public static string Repairs_ErrorUpdating {
            get {
                return ResourceManager.GetString("Repairs.ErrorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;&lt;br /&gt;
        ///
        ///&lt;b&gt;Status Update for your equipment:&lt;/b&gt;
        ///&lt;ul&gt;
        ///  &lt;li&gt;&lt;b&gt;Machine:&lt;/b&gt; {1}&lt;/li&gt;
        ///  &lt;li&gt;&lt;b&gt;Serial Number:&lt;/b&gt; {2}&lt;/li&gt;
        ///  &lt;li&gt;&lt;b&gt;Job Card:&lt;/b&gt; {4}&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;{3}&lt;/p&gt;.
        /// </summary>
        public static string Repairs_StatusEmailBody {
            get {
                return ResourceManager.GetString("Repairs.StatusEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Status Update.
        /// </summary>
        public static string Repairs_StatusEmailSubject {
            get {
                return ResourceManager.GetString("Repairs.StatusEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair status updated successfully.
        /// </summary>
        public static string Repairs_StatusUpdateSuccess {
            get {
                return ResourceManager.GetString("Repairs.StatusUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security configuration detected.
        /// </summary>
        public static string Security_InvalidSecret {
            get {
                return ResourceManager.GetString("Security.InvalidSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security configuration error - please contact administrator.
        /// </summary>
        public static string Security_InvalidSecretConfig {
            get {
                return ResourceManager.GetString("Security.InvalidSecretConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HTTP context available for operation.
        /// </summary>
        public static string Security_NoHttpContext {
            get {
                return ResourceManager.GetString("Security.NoHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security token is invalid or expired.
        /// </summary>
        public static string Security_TokenInvalid {
            get {
                return ResourceManager.GetString("Security.TokenInvalid", resourceCulture);
            }
        }
    }
}
