//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class ChangePasswordSuccess
    {
        protected global::System.Web.UI.WebControls.Content HeaderContent;
        protected global::System.Web.UI.WebControls.Content BodyContent;
    }
}
