//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class ChangePassword
    {
        protected global::System.Web.UI.WebControls.Content HeaderContent;
        protected global::System.Web.UI.WebControls.Content BodyContent;
        protected global::System.Web.UI.WebControls.ChangePassword ChangeUserPassword;
        protected global::System.Web.UI.WebControls.Literal FailureText;
        protected global::System.Web.UI.WebControls.ValidationSummary ChangeUserPasswordValidationSummary;
        protected global::System.Web.UI.WebControls.Label CurrentPasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox CurrentPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator CurrentPasswordRequired;
        protected global::System.Web.UI.WebControls.Label NewPasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox NewPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator NewPasswordRequired;
        protected global::System.Web.UI.WebControls.Label ConfirmNewPasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox ConfirmNewPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator ConfirmNewPasswordRequired;
        protected global::System.Web.UI.WebControls.CompareValidator NewPasswordCompare;
        protected global::System.Web.UI.WebControls.Button CancelPushButton;
        protected global::System.Web.UI.WebControls.Button ChangePasswordPushButton;
    }
}
