//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class Register
    {
        protected global::System.Web.UI.WebControls.Content HeaderContent;
        protected global::System.Web.UI.WebControls.Content BodyContent;
        protected global::System.Web.UI.WebControls.CreateUserWizard RegisterUser;
        protected global::System.Web.UI.WebControls.PlaceHolder wizardStepPlaceholder;
        protected global::System.Web.UI.WebControls.PlaceHolder navigationPlaceholder;
        protected global::System.Web.UI.WebControls.CreateUserWizardStep RegisterUserWizardStep;
        protected global::System.Web.UI.WebControls.Literal ErrorMessage;
        protected global::System.Web.UI.WebControls.ValidationSummary RegisterUserValidationSummary;
        protected global::System.Web.UI.WebControls.Label UserNameLabel;
        protected global::System.Web.UI.WebControls.TextBox UserName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator UserNameRequired;
        protected global::System.Web.UI.WebControls.Label EmailLabel;
        protected global::System.Web.UI.WebControls.TextBox Email;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator EmailRequired;
        protected global::System.Web.UI.WebControls.Label PasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox Password;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator PasswordRequired;
        protected global::System.Web.UI.WebControls.Label ConfirmPasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator ConfirmPasswordRequired;
        protected global::System.Web.UI.WebControls.CompareValidator PasswordCompare;
        protected global::System.Web.UI.WebControls.Button CreateUserButton;
        protected global::System.Web.UI.WebControls.Button ContinueButton;
        protected global::System.Web.UI.WebControls.Button StepPreviousButton;
        protected global::System.Web.UI.WebControls.Button StepNextButton;
    }
}
