//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class ClientList
    {
        /*
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.Label lblRoastDate;
        protected global::System.Web.UI.WebControls.TextBox tbxCompanyName;
        protected global::System.Web.UI.WebControls.Button btnGo;
        protected global::System.Web.UI.WebControls.DropDownList ddlClientEnabled;
        protected global::System.Web.UI.WebControls.DropDownList ddlClientsPerPage;
        protected global::System.Web.UI.WebControls.Button btnSendBulkEmail;
        protected global::System.Web.UI.WebControls.ScriptManager smClientDetails;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgClientDetails;
        protected global::System.Web.UI.WebControls.Literal ltrlProgessTest;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSendEmail;
        protected global::System.Web.UI.WebControls.TextBox tbxSubject;
        protected global::System.Web.UI.WebControls.TextBox tbxTime;
        protected global::System.Web.UI.WebControls.CheckBox cbxSendTest;
        protected global::System.Web.UI.WebControls.TextBox tbxTestEmail;
        protected global::System.Web.UI.WebControls.Button btnSendIt;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Literal ltrlEmailStatus;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlClientDetails;
        protected global::System.Web.UI.WebControls.GridView gvClients;
        protected global::System.Web.UI.WebControls.TextBox tbxContactFirstname;
        protected global::System.Web.UI.WebControls.Label lblContactFirstName;
        protected global::System.Web.UI.WebControls.TextBox tbxContactLastName;
        protected global::System.Web.UI.WebControls.Label lblContactLastName;
        protected global::System.Web.UI.WebControls.Literal ltrlFilter;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsCustomers;
        */
    }
}
