//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class CoffeeRequired
    {
        /*
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smgrRequired;
        protected global::System.Web.UI.WebControls.UpdateProgress uppgRequired;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlRequired;
        protected global::System.Web.UI.WebControls.GridView gvPreperationDay;
        protected global::System.Web.UI.WebControls.Label lblGroupTitle;
        protected global::System.Web.UI.WebControls.Label lblItemDesc;
        protected global::System.Web.UI.WebControls.Label lblQty;
        protected global::System.Web.UI.WebControls.Label lblFooterQty;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsRequiredByRoastingDay;
        protected global::System.Web.UI.WebControls.GridView gvCoffeeRequireByDay;
        protected global::System.Web.UI.WebControls.Label lblByGroupTitle;
        protected global::System.Web.UI.WebControls.Label lblByAbreviation;
        protected global::System.Web.UI.WebControls.Label lblByItemDesc;
        protected global::System.Web.UI.WebControls.Label lblByFooterQty;
        protected global::System.Web.UI.WebControls.Label lblByQty;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsCoffeeRequiredCalc;
        */
    }
}
