//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class DeleteOrderLine
    {
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.DetailsView dvDeleteOrderItem;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsOrderLine;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.Button btnReturn;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
    }
}
