//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class GroupItemDetail
    {
        /*
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager scmGroupDetail;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlGroupDetail;
        protected global::System.Web.UI.WebControls.Label lblAddOrEditItem;
        protected global::System.Web.UI.WebControls.TextBox tbxGroupItem;
        protected global::System.Web.UI.WebControls.Label lblGroupItemID;
        protected global::System.Web.UI.WebControls.TextBox tbxGroupDesc;
        protected global::System.Web.UI.WebControls.TextBox tbxGroupShortName;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        */
    }
}
