//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Pages
{
    public partial class ItemsRequired
    {
        protected global::System.Web.UI.ScriptManager smgrRequired;
        protected global::System.Web.UI.UpdateProgress uppgRequired;
        protected global::System.Web.UI.UpdatePanel upnlRequired;
        protected global::System.Web.UI.WebControls.Panel pnlItemsRequired;
        protected global::System.Web.UI.WebControls.TextBox tbxDateFrom;
        protected global::System.Web.UI.WebControls.ImageButton btnCalendarFrom;
        protected global::AjaxControlToolkit.CalendarExtender tbxDateFrom_CalendarExtender;
        protected global::System.Web.UI.WebControls.TextBox tbxDateTo;
        protected global::System.Web.UI.WebControls.ImageButton btnCalendarTo;
        protected global::AjaxControlToolkit.CalendarExtender tbxDateTo_CalendarExtender;
        protected global::System.Web.UI.WebControls.Button GoBtn;
        protected global::System.Web.UI.WebControls.Button ResetBtn;
        protected global::System.Web.UI.WebControls.Button PrevWeekBtn;
        protected global::System.Web.UI.WebControls.Button NextWeekBtn;
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlStatus;
        protected global::System.Web.UI.WebControls.Label lblFilterStatus;
        protected global::AjaxControlToolkit.TabContainer tabRequired;
        protected global::AjaxControlToolkit.TabPanel pnlByPrepDate;
        protected global::System.Web.UI.WebControls.GridView gvPreparationDay;
        protected global::AjaxControlToolkit.TabPanel tabpnlRequiredDetail;
        protected global::System.Web.UI.WebControls.GridView gvItemsRequiredByDay;
    }
}
