//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class OrdersEdit
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smgrOrdersEdit;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlButtonBar;
        protected global::System.Web.UI.WebControls.Button btnNew;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterBy;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.CheckBox cbxOnlyToDo;
        protected global::System.Web.UI.WebControls.Button btnGo;
        protected global::System.Web.UI.WebControls.DropDownList ddlOrdersPerPage;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgOrderEditDetail;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlOrderEditDetail;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
        protected global::System.Web.UI.WebControls.DetailsView dvOrderEdit;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomer;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomer;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomer;
        protected global::System.Web.UI.WebControls.TextBox tbxDetailOrderDate;
        protected global::System.Web.UI.WebControls.TextBox tbxDetailOrderDate;
        protected global::System.Web.UI.WebControls.Label lblOrderDate;
        protected global::System.Web.UI.WebControls.TextBox tbxDetailRoastDate;
        protected global::System.Web.UI.WebControls.TextBox tbxDetailRoastDate;
        protected global::System.Web.UI.WebControls.Label lblRoastDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemDesc;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemDesc;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemDesc;
        protected global::System.Web.UI.WebControls.TextBox tbxQuantity;
        protected global::System.Web.UI.WebControls.TextBox tbxQuantity;
        protected global::System.Web.UI.WebControls.Label lblQuantity;
        protected global::System.Web.UI.WebControls.TextBox tbxRequiredByDate;
        protected global::System.Web.UI.WebControls.TextBox tbxRequiredByDate;
        protected global::System.Web.UI.WebControls.TextBox tbxRequiredByDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.CheckBox cbxConfirmed;
        protected global::System.Web.UI.WebControls.CheckBox cbxConfirmed;
        protected global::System.Web.UI.WebControls.CheckBox cbxConfirmed;
        protected global::System.Web.UI.WebControls.TextBox tbxNotes;
        protected global::System.Web.UI.WebControls.TextBox tbxNotes;
        protected global::System.Web.UI.WebControls.Label lblNotes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsOrderDetail;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsCompanyNames;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemTypes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsDeliveryBy;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgOrdersEdit;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlOrdersEditList;
        protected global::System.Web.UI.WebControls.GridView gvOrdersEditList;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomer;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomer;
        protected global::System.Web.UI.WebControls.Label lblCompany;
        protected global::System.Web.UI.WebControls.HyperLink hlCompany;
        protected global::System.Web.UI.WebControls.TextBox tbxOrderDate;
        protected global::System.Web.UI.WebControls.TextBox tbxOrderDate;
        protected global::System.Web.UI.WebControls.Label lblOrderDate;
        protected global::System.Web.UI.WebControls.TextBox tbxRoastDate;
        protected global::System.Web.UI.WebControls.TextBox tbxRoastDate;
        protected global::System.Web.UI.WebControls.Label lblRoastDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemDesc;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemDesc;
        protected global::System.Web.UI.WebControls.Label lblItemDesc;
        protected global::System.Web.UI.WebControls.TextBox tbxRequiredByDate;
        protected global::System.Web.UI.WebControls.TextBox tbxRequiredByDate;
        protected global::System.Web.UI.WebControls.Label lblRequiredByDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.Label lblItemTemplate;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsOrdersTbl;
        protected global::System.Web.UI.WebControls.Literal ltrlFilter;
        */
    }
}
