//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Pages
{
    public partial class OrderDone
    {
        protected global::System.Web.UI.ScriptManager smOrderDone;
        protected global::System.Web.UI.UpdateProgress updtprgOrderDone;
        protected global::System.Web.UI.UpdatePanel updtpnlOrderDone;
        protected global::System.Web.UI.WebControls.Panel pnlOrderShell;
        protected global::System.Web.UI.WebControls.Panel pnlOrderDetails;
        protected global::System.Web.UI.WebControls.FormView fvOrderDone;
        protected global::System.Web.UI.WebControls.GridView gvOrderDoeLines;
        protected global::System.Web.UI.WebControls.TextBox tbxStock;
        protected global::System.Web.UI.WebControls.RadioButtonList rbtnSendConfirm;
        protected global::System.Web.UI.WebControls.TextBox tbxCount;
        protected global::System.Web.UI.WebControls.Button btnDone;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Panel pnlCustomerDetailsUpdated;
        protected global::System.Web.UI.WebControls.Label tbxCustomerName;
        protected global::System.Web.UI.WebControls.DataGrid dgCustomerUsage;
        protected global::System.Web.UI.WebControls.Button btnReturnToDeliveres;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlStatus;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsOrderDoneHeader;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsOrderDoneLines;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemTypes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsPackagingTypes;
    }
}
