//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Pages
{
    public partial class OrderDetail
    {
        protected global::System.Web.UI.WebControls.Panel pnlOrderShell;
        protected global::System.Web.UI.WebControls.Image imgPageToneIcon;
        protected global::System.Web.UI.UpdatePanel upnlPageTitle;
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litPageSubtitle;
        protected global::System.Web.UI.WebControls.Panel pnlNewWooOrders;
        protected global::System.Web.UI.WebControls.Literal litNewWooOrdersPrompt;
        protected global::System.Web.UI.WebControls.Button btnNewWooOrdersImport;
        protected global::System.Web.UI.WebControls.Button btnNewWooOrdersContinue;
        protected global::System.Web.UI.ScriptManager scrmOrderDetail;
        protected global::System.Web.UI.UpdateProgress udtpOrderDetail;
        protected global::System.Web.UI.UpdatePanel upnlSaveReturnRedirect;
        protected global::System.Web.UI.WebControls.HiddenField hdnSaveReturnRedirectUrl;
        protected global::System.Web.UI.WebControls.Panel pnlOrderConflictShell;
        protected global::System.Web.UI.UpdatePanel upnlOrderConflict;
        protected global::System.Web.UI.WebControls.Panel pnlOrderConflict;
        protected global::System.Web.UI.WebControls.Literal litConflictMessage;
        protected global::System.Web.UI.WebControls.Panel pnlAddLineConflictActions;
        protected global::System.Web.UI.WebControls.Button btnUseExistingOrder;
        protected global::System.Web.UI.WebControls.Button btnCreateNewOrderAnyway;
        protected global::System.Web.UI.WebControls.Button btnOpenExistingOrder;
        protected global::System.Web.UI.WebControls.Button btnDismissConflict;
        protected global::System.Web.UI.WebControls.Panel pnlMergePromptActions;
        protected global::System.Web.UI.WebControls.Button btnConfirmMergeDuplicate;
        protected global::System.Web.UI.WebControls.Button btnOpenDuplicateOrder;
        protected global::System.Web.UI.WebControls.Button btnDismissMergePrompt;
        protected global::System.Web.UI.UpdatePanel pnlOrderHeader;
        protected global::System.Web.UI.WebControls.HyperLink hlContactHdr;
        protected global::AjaxControlToolkit.ComboBox cboContacts;
        protected global::System.Web.UI.WebControls.HiddenField hdnSelectedContactId;
        protected global::System.Web.UI.WebControls.TextBox tbxOrderDate;
        protected global::AjaxControlToolkit.CalendarExtender tbxOrderDate_CalendarExtender;
        protected global::System.Web.UI.WebControls.TextBox tbxPrepDate;
        protected global::AjaxControlToolkit.CalendarExtender tbxPrepDate_CalendarExtender;
        protected global::System.Web.UI.WebControls.DropDownList ddlToBeDeliveredBy;
        protected global::System.Web.UI.WebControls.TextBox tbxRequiredByDate;
        protected global::AjaxControlToolkit.CalendarExtender tbxRequiredByDate_CalendarExtender;
        protected global::System.Web.UI.WebControls.TextBox tbxPurchaseOrder;
        protected global::System.Web.UI.WebControls.CheckBox cbxConfirmed;
        protected global::System.Web.UI.WebControls.CheckBox cbxInvoiceDone;
        protected global::System.Web.UI.WebControls.CheckBox cbxDone;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trWooLink;
        protected global::System.Web.UI.WebControls.HyperLink hlWooOrder;
        protected global::System.Web.UI.WebControls.Label lblWooOrder;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trWaybill;
        protected global::System.Web.UI.WebControls.Label lblDispatchStatus;
        protected global::System.Web.UI.WebControls.Label lblWaybill;
        protected global::System.Web.UI.WebControls.ImageButton btnEditWaybill;
        protected global::System.Web.UI.UpdatePanel upnlWaybillEdit;
        protected global::System.Web.UI.WebControls.Panel pnlWaybillEdit;
        protected global::System.Web.UI.WebControls.Label lblWaybillEditNumber;
        protected global::System.Web.UI.WebControls.TextBox tbxWaybillEdit;
        protected global::System.Web.UI.WebControls.Label lblWaybillEditCourier;
        protected global::System.Web.UI.WebControls.DropDownList ddlWaybillCourier;
        protected global::System.Web.UI.WebControls.CheckBox cbxNotifyWaybillChange;
        protected global::System.Web.UI.WebControls.Button btnUpdateWaybill;
        protected global::System.Web.UI.WebControls.Button btnCancelWaybillEdit;
        protected global::System.Web.UI.WebControls.TextBox tbxNotes;
        protected global::System.Web.UI.WebControls.HiddenField hdnHeaderDirty;
        protected global::System.Web.UI.WebControls.Button btnSaveHeader;
        protected global::System.Web.UI.WebControls.Button btnSaveAndReturn;
        protected global::System.Web.UI.HtmlControls.HtmlButton btnUndoHeader;
        protected global::System.Web.UI.WebControls.Button btnLastOrder;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spnWooLink;
        protected global::System.Web.UI.WebControls.ImageButton btnWooLink;
        protected global::System.Web.UI.UpdatePanel upnlWooLink;
        protected global::System.Web.UI.WebControls.Panel pnlWooLink;
        protected global::System.Web.UI.WebControls.Literal litWooLinkPrompt;
        protected global::System.Web.UI.WebControls.RadioButtonList rblWooLinkCandidates;
        protected global::System.Web.UI.WebControls.Button btnWooLinkConfirm;
        protected global::System.Web.UI.WebControls.Button btnWooLinkCancel;
        protected global::System.Web.UI.UpdatePanel upnlOrderLines;
        protected global::System.Web.UI.WebControls.GridView gvOrderLines;
        protected global::System.Web.UI.UpdatePanel upnlNewOrderItem;
        protected global::System.Web.UI.WebControls.Button btnNewItem;
        protected global::System.Web.UI.WebControls.Panel pnlNewItem;
        protected global::AjaxControlToolkit.ComboBox cboNewItemDesc;
        protected global::System.Web.UI.WebControls.TextBox tbxNewQuantityOrdered;
        protected global::AjaxControlToolkit.ComboBox cboNewPackaging;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.UpdatePanel updtButtonPanel;
        protected global::System.Web.UI.WebControls.Button btnNewOrder;
        protected global::System.Web.UI.WebControls.Button btnConfirmOrder;
        protected global::System.Web.UI.WebControls.Button btnMerge;
        protected global::System.Web.UI.WebControls.Button btnDlSheet;
        protected global::System.Web.UI.WebControls.Button btnOrderCancelled;
        protected global::System.Web.UI.WebControls.Button btnUnDoDone;
        protected global::System.Web.UI.WebControls.Button btnOrderDelivered;
        protected global::System.Web.UI.WebControls.ImageButton btnBack;
        protected global::System.Web.UI.UpdatePanel upnlStatus;
        protected global::System.Web.UI.WebControls.Panel pnlStatusMessage;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
    }
}
