//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class OrderEntry
    {
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.CheckBox chkbxOrderDone;
        protected global::System.Web.UI.WebControls.DropDownList ddlSearchFor;
        protected global::System.Web.UI.WebControls.TextBox tbxSearchFor;
        protected global::System.Web.UI.WebControls.Button btnGo;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsDistinctOrders;
        protected global::System.Web.UI.WebControls.GridView gvListOfOrders;
        protected global::System.Web.UI.WebControls.DropDownList ddlCompany;
        protected global::System.Web.UI.WebControls.Label lblCompany;
        protected global::System.Web.UI.WebControls.DropDownList ddlPersons;
        protected global::System.Web.UI.WebControls.Label lblPerson;
        protected global::System.Web.UI.WebControls.DropDownList ddlImte;
        protected global::System.Web.UI.WebControls.Label ItemDescLabel;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsOrdersDetail;
        protected global::System.Web.UI.WebControls.GridView gvOrderDetails;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsCompanys;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsPersons;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItems;
    }
}
