//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class OrderSheet
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smgrOrdersSheet;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgOrderEditDetail;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlButtonBar;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterBy;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.Button btnGo;
        protected global::System.Web.UI.WebControls.CheckBox cbxOrdersToDo;
        protected global::System.Web.UI.WebControls.Button btnPrint;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlOrderSheet;
        protected global::System.Web.UI.WebControls.GridView gvOrderSheet;
        protected global::System.Web.UI.WebControls.Literal ltrlFilter;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsOrderSheet;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsDeliveryBy;
        protected global::System.Web.UI.WebControls.Table tblTotalsSummary;
        */
    }
}
