//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Pages
{
    public partial class SentRemindersSheet
    {
        protected global::System.Web.UI.ScriptManager smSentRemindersSummary;
        protected global::System.Web.UI.UpdateProgress uprgSentRemindersSummary;
        protected global::System.Web.UI.UpdatePanel upnlSentRemindersList;
        protected global::System.Web.UI.WebControls.Panel pnlReminders;
        protected global::System.Web.UI.WebControls.Label lblFilterByDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterByDate;
        protected global::System.Web.UI.WebControls.Button btnRefresh;
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.WebControls.Literal ltrlReminderSummary;
        protected global::System.Web.UI.WebControls.GridView gvSentReminders;
        protected global::System.Web.UI.WebControls.Literal ltrlReminderFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFailedEmails;
        protected global::System.Web.UI.WebControls.GridView gvFailedEmails;
        protected global::System.Web.UI.WebControls.Button btnClearFailures;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlStatus;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
    }
}
