//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Pages
{
    public partial class SupportTables
    {
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.ScriptManager smSupporTables;
        protected global::System.Web.UI.UpdateProgress uprgSupporTables;
        protected global::System.Web.UI.WebControls.DropDownList ddlTables;
        protected global::System.Web.UI.UpdatePanel upnlSupporTables;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.GridView gvSupporTable;
    }
}
