//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class SupportTables
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smSupporTables;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgSupporTables;
        protected global::System.Web.UI.WebControls.DropDownList ddlTables;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSupporTables;
        protected global::System.Web.UI.WebControls.GridView gvSupporTable;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemTypeTbl;

        */
    }
}
