//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class ThisWeeksOrder
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smOrderSummary;
        protected global::System.Web.UI.WebControls.DropDownList ddlOrdersPerPage;
        protected global::System.Web.UI.WebControls.UpdateProgress uproOrderSummary;
        protected global::System.Web.UI.WebControls.UpdatePanel upanOrderSummary;
        protected global::System.Web.UI.WebControls.GridView gvOutstandingOrders;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsOpenOrders;
        */
    }
}
