//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TrackerSQL.Pages
{
    public partial class ViewMyOrder
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl hdrTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl hdrMeta;
        protected global::System.Web.UI.WebControls.Literal litHeaderNotes;
        protected global::System.Web.UI.WebControls.PlaceHolder phError;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl errBox;
        protected global::System.Web.UI.WebControls.PlaceHolder phOrder;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tbodyLines;
        protected global::System.Web.UI.WebControls.Literal litTotalLines;
        protected global::System.Web.UI.WebControls.Literal litChangeResult;
        protected global::System.Web.UI.WebControls.TextBox tbxChangeRequest;
        protected global::System.Web.UI.WebControls.Button btnSubmitChange;
    }
}