//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class DatabaseBackup
    {
        // Control fields are declared in DatabaseBackup.aspx.cs
    }
}
