//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class DeliveryPromiseRules
    {
        protected global::System.Web.UI.ScriptManager smDeliveryPromise;
        protected global::System.Web.UI.UpdateProgress upgDeliveryPromise;
        protected global::System.Web.UI.WebControls.Panel pnlAccessDenied;
        protected global::System.Web.UI.WebControls.Label lblAccessDenied;
        protected global::System.Web.UI.UpdatePanel upnlDeliveryPromise;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlStatus;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
        protected global::System.Web.UI.WebControls.Label lblSearch;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Label lblFilterGroup;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterGroup;
        protected global::System.Web.UI.WebControls.CheckBox chkShowDisabled;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnShowAddPanel;
        protected global::System.Web.UI.WebControls.Panel pnlAddInline;
        protected global::System.Web.UI.WebControls.TextBox txtNewGroup;
        protected global::System.Web.UI.WebControls.TextBox txtNewAreaName;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewArea;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewStartDow;
        protected global::System.Web.UI.WebControls.TextBox txtNewStartTime;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewEndDow;
        protected global::System.Web.UI.WebControls.TextBox txtNewEndTime;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewKind;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewResultMode;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewResultDow;
        protected global::System.Web.UI.WebControls.Button btnAddRule;
        protected global::System.Web.UI.WebControls.Button btnCancelAdd;
        protected global::System.Web.UI.WebControls.GridView gvRules;
        protected global::System.Web.UI.WebControls.ImageButton btnBack;
    }
}
