//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class DriverApp
    {
        protected global::System.Web.UI.WebControls.Panel pnlSettings;

        protected global::System.Web.UI.WebControls.Literal litMessage;

        protected global::System.Web.UI.WebControls.CheckBox chkRunDone;

        protected global::System.Web.UI.WebControls.CheckBox chkSendConfirmation;

        protected global::System.Web.UI.WebControls.CheckBox chkNotesToOffice;

        protected global::System.Web.UI.WebControls.TextBox txtOfficeEmail;

        protected global::System.Web.UI.WebControls.Literal litOrdersEmail;

        protected global::System.Web.UI.WebControls.Button btnSaveSettings;

        protected global::System.Web.UI.WebControls.Literal litSettingsInfo;

        protected global::System.Web.UI.WebControls.Panel pnlApk;

        protected global::System.Web.UI.WebControls.Literal litApkInfo;

        protected global::System.Web.UI.WebControls.Panel pnlNoApk;
    }
}
