//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL
{
    public partial class GenMachineKeys
    {
        protected global::System.Web.UI.WebControls.Button btnGo;
        protected global::System.Web.UI.WebControls.Label lblMachineKeys;
    }
}
