//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class HolidayClosureDetail
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.ScriptManager smClosureDetail;
        protected global::System.Web.UI.UpdateProgress upgClosureDetail;
        protected global::System.Web.UI.UpdatePanel upnlDetail;
        protected global::System.Web.UI.WebControls.HiddenField hdnClosureId;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Literal litPanelTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.ImageButton imgCalendarDate;
        protected global::AjaxControlToolkit.CalendarExtender calDetailDate;
        protected global::System.Web.UI.WebControls.TextBox txtDays;
        protected global::System.Web.UI.WebControls.DropDownList ddlStrategy;
        protected global::System.Web.UI.WebControls.CheckBox chkPrep;
        protected global::System.Web.UI.WebControls.CheckBox chkDelivery;
        protected global::System.Web.UI.WebControls.TextBox txtDesc;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnSaveReturn;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.ImageButton btnBack;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlStatus;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
    }
}
