//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class MessagesEditor
    {
        protected global::System.Web.UI.ScriptManager smgrMessagesEditor;
        protected global::System.Web.UI.UpdateProgress udpMessagesEditor;
        protected global::System.Web.UI.WebControls.Panel pnlAccessDenied;
        protected global::System.Web.UI.WebControls.Literal ltrlAccessDenied;
        protected global::System.Web.UI.UpdatePanel upnlMessagesEditor;
        protected global::System.Web.UI.WebControls.Panel pnlEditor;
        protected global::System.Web.UI.WebControls.TextBox tbxSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlResultsSection;
        protected global::System.Web.UI.WebControls.Label ResultsTitleLabel;
        protected global::System.Web.UI.WebControls.GridView gvMessages;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlStatus;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
    }
}
