//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class SystemTools
    {
        protected global::System.Web.UI.ScriptManager tsmSystemTools;
        protected global::System.Web.UI.WebControls.Panel pnlSystemTools;
        protected global::System.Web.UI.UpdateProgress uprgSystemTools;
        protected global::System.Web.UI.UpdatePanel upnlSystemToolsButtons;
        protected global::System.Web.UI.WebControls.Button btnXMLTOSQL;
        protected global::System.Web.UI.WebControls.Button btnResetPrepDates;
        protected global::System.Web.UI.WebControls.Button btnMoveDlvryDate;
        protected global::System.Web.UI.WebControls.Button btnHolidayClosures;
        protected global::System.Web.UI.WebControls.Button btnEditSystemData;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlWooMappingTool;
        protected global::System.Web.UI.WebControls.Literal litWooMappingToolBlurb;
        protected global::System.Web.UI.WebControls.Button btnWooMapping;
        protected global::System.Web.UI.WebControls.Button btnLogViewer;
        protected global::System.Web.UI.WebControls.Button btnEmailDiagnostics;
        protected global::System.Web.UI.WebControls.Button btnSetLastOrderDate;
        protected global::System.Web.UI.WebControls.CheckBox chkRecalcPredictionsStaleOnly;
        protected global::System.Web.UI.WebControls.Button btnRecalcPredictions;
        protected global::System.Web.UI.WebControls.Button btnMessagesEditor;
        protected global::System.Web.UI.WebControls.Button btnDatabaseBackup;
        protected global::System.Web.UI.WebControls.Button btnSqlConnectionTest;
        protected global::System.Web.UI.WebControls.Button btnDisableInactiveClients;
        protected global::System.Web.UI.WebControls.Panel pnlResultsSection;
        protected global::System.Web.UI.WebControls.Panel pnlToolResults;
        protected global::System.Web.UI.WebControls.Label ResultsTitleLabel;
        protected global::System.Web.UI.WebControls.GridView gvResults;
        protected global::System.Web.UI.WebControls.Panel pnlResetPrepDate;
        protected global::System.Web.UI.WebControls.GridView gvAreaPrepDates;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlStatus;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
    }
}
