//------------------------------------------------------------------------------
// <auto-generated>
//     Designer support file for SystemPreferences.aspx
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class SystemPreferences
    {
        protected global::System.Web.UI.ScriptManager smSysPrefs;
        protected global::System.Web.UI.UpdateProgress updtPrgSysPrefs;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsSysData;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemServiceTypes;
        protected global::System.Web.UI.UpdatePanel upnlSysPrefs;
        protected global::System.Web.UI.WebControls.Panel pnlAccessDenied;
        protected global::System.Web.UI.WebControls.Label lblAccessDenied;
        protected global::System.Web.UI.WebControls.Panel pnlSysPrefs;
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litPageSubtitle;
        protected global::System.Web.UI.WebControls.Literal litSectionsHeading;
        protected global::System.Web.UI.WebControls.LinkButton btnNavGeneral;
        protected global::System.Web.UI.WebControls.LinkButton btnNavWoo;
        protected global::System.Web.UI.WebControls.MultiView mvSections;
        protected global::System.Web.UI.WebControls.View viewGeneral;
        protected global::System.Web.UI.WebControls.DetailsView dvSystemData;
        protected global::System.Web.UI.WebControls.View viewWoo;
        protected global::System.Web.UI.WebControls.Literal litWooSectionTitle;
        protected global::System.Web.UI.WebControls.Panel pnlWooHome;
        protected global::System.Web.UI.WebControls.Literal litWooStatus;
        protected global::System.Web.UI.WebControls.Literal litPhase2Note;
        protected global::System.Web.UI.WebControls.Button btnStartWizard;
        protected global::System.Web.UI.WebControls.HyperLink hlWooMapping;
        protected global::System.Web.UI.WebControls.Panel pnlWooSettings;
        protected global::System.Web.UI.WebControls.Literal litLblStoreUrl;
        protected global::System.Web.UI.WebControls.TextBox txtStoreUrl;
        protected global::System.Web.UI.WebControls.Literal litLblAdminUrl;
        protected global::System.Web.UI.WebControls.TextBox txtAdminUrl;
        protected global::System.Web.UI.WebControls.Literal litLblKey;
        protected global::System.Web.UI.WebControls.TextBox txtConsumerKey;
        protected global::System.Web.UI.WebControls.Button btnToggleKeyHome;
        protected global::System.Web.UI.WebControls.Literal litLblSecret;
        protected global::System.Web.UI.WebControls.TextBox txtConsumerSecret;
        protected global::System.Web.UI.WebControls.Button btnToggleSecretHome;
        protected global::System.Web.UI.WebControls.Literal litSavedKeyHint;
        protected global::System.Web.UI.WebControls.Button btnSaveWooCreds;
        protected global::System.Web.UI.WebControls.Button btnTestWoo;
        protected global::System.Web.UI.WebControls.Panel pnlEnableNext;
        protected global::System.Web.UI.WebControls.Literal litEnableNextHint;
        protected global::System.Web.UI.WebControls.CheckBox chkOpenMappingAfterEnable;
        protected global::System.Web.UI.WebControls.Literal litOpenMappingAfterEnable;
        protected global::System.Web.UI.WebControls.Button btnEnableWoo;
        protected global::System.Web.UI.WebControls.Panel pnlDisableNext;
        protected global::System.Web.UI.WebControls.Literal litDisableHint;
        protected global::System.Web.UI.WebControls.Button btnDisableWoo;
        protected global::System.Web.UI.WebControls.Button btnRerunWizard;
        protected global::System.Web.UI.WebControls.Panel pnlWizard;
        protected global::System.Web.UI.WebControls.Literal litProgressLabel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liProg1;
        protected global::System.Web.UI.WebControls.Literal litProg1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liProg2;
        protected global::System.Web.UI.WebControls.Literal litProg2;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liProg3;
        protected global::System.Web.UI.WebControls.Literal litProg3;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liProg4;
        protected global::System.Web.UI.WebControls.Literal litProg4;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liProg5;
        protected global::System.Web.UI.WebControls.Literal litProg5;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liProg6;
        protected global::System.Web.UI.WebControls.Literal litProg6;
        protected global::System.Web.UI.WebControls.MultiView mvWizard;
        protected global::System.Web.UI.WebControls.View wizPrep;
        protected global::System.Web.UI.WebControls.Literal litWizPrepTitle;
        protected global::System.Web.UI.WebControls.Literal litWizPrepBody;
        protected global::System.Web.UI.WebControls.View wizSchema;
        protected global::System.Web.UI.WebControls.Literal litWizSchemaTitle;
        protected global::System.Web.UI.WebControls.Literal litWizSchemaBody;
        protected global::System.Web.UI.WebControls.Button btnEnsureSchema;
        protected global::System.Web.UI.WebControls.View wizCreds;
        protected global::System.Web.UI.WebControls.Literal litWizCredsTitle;
        protected global::System.Web.UI.WebControls.Literal litWizLblStore;
        protected global::System.Web.UI.WebControls.TextBox txtWizStoreUrl;
        protected global::System.Web.UI.WebControls.Literal litWizLblAdmin;
        protected global::System.Web.UI.WebControls.TextBox txtWizAdminUrl;
        protected global::System.Web.UI.WebControls.Literal litWizLblKey;
        protected global::System.Web.UI.WebControls.TextBox txtWizKey;
        protected global::System.Web.UI.WebControls.Button btnToggleKeyWiz;
        protected global::System.Web.UI.WebControls.Literal litWizLblSecret;
        protected global::System.Web.UI.WebControls.TextBox txtWizSecret;
        protected global::System.Web.UI.WebControls.Button btnToggleSecretWiz;
        protected global::System.Web.UI.WebControls.Button btnWizSaveCreds;
        protected global::System.Web.UI.WebControls.View wizTest;
        protected global::System.Web.UI.WebControls.Literal litWizTestTitle;
        protected global::System.Web.UI.WebControls.Literal litWizTestBody;
        protected global::System.Web.UI.WebControls.Button btnWizTest;
        protected global::System.Web.UI.WebControls.View wizOptions;
        protected global::System.Web.UI.WebControls.Literal litWizOptionsTitle;
        protected global::System.Web.UI.WebControls.Literal litWizLblCat;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoryMode;
        protected global::System.Web.UI.WebControls.Literal litWizLblDispatch;
        protected global::System.Web.UI.WebControls.TextBox txtDispatchIds;
        protected global::System.Web.UI.WebControls.CheckBox chkTrackingRequired;
        protected global::System.Web.UI.WebControls.Literal litWizLblTracking;
        protected global::System.Web.UI.WebControls.Button btnWizSaveOptions;
        protected global::System.Web.UI.WebControls.View wizFinish;
        protected global::System.Web.UI.WebControls.Literal litWizFinishTitle;
        protected global::System.Web.UI.WebControls.Literal litWizFinishBody;
        protected global::System.Web.UI.WebControls.CheckBox chkOpenMappingAfterFinish;
        protected global::System.Web.UI.WebControls.Literal litOpenMappingAfterFinish;
        protected global::System.Web.UI.WebControls.Button btnWizFinish;
        protected global::System.Web.UI.WebControls.Button btnWizBack;
        protected global::System.Web.UI.WebControls.Button btnWizNext;
        protected global::System.Web.UI.WebControls.Button btnWizCancel;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
