//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class WooOrderImport
    {
        protected global::System.Web.UI.WebControls.Panel pnlAccessDenied;
        protected global::System.Web.UI.WebControls.Label lblAccessDenied;
        protected global::System.Web.UI.WebControls.Panel pnlWooDisabled;
        protected global::System.Web.UI.WebControls.Literal litWooDisabled;
        protected global::System.Web.UI.WebControls.Button btnStartWooWizard;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.HyperLink lnkPaymentMaps;
        protected global::System.Web.UI.WebControls.Panel pnlStatus;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Label lblMode;
        protected global::System.Web.UI.WebControls.DropDownList ddlMode;
        protected global::System.Web.UI.WebControls.Panel pnlSpecific;
        protected global::System.Web.UI.WebControls.Label lblOrderId;
        protected global::System.Web.UI.WebControls.TextBox txtOrderId;
        protected global::System.Web.UI.WebControls.Panel pnlDateRange;
        protected global::System.Web.UI.WebControls.Label lblFrom;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.Label lblTo;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnPull;
        protected global::System.Web.UI.WebControls.Button btnClearPreview;
        protected global::System.Web.UI.WebControls.Literal litLastSync;
        protected global::System.Web.UI.WebControls.CheckBox chkUpdateExisting;
        protected global::System.Web.UI.WebControls.GridView gvPreview;
        protected global::System.Web.UI.WebControls.Panel pnlResults;
        protected global::System.Web.UI.WebControls.BulletedList blResults;
        protected global::System.Web.UI.WebControls.Button btnRefreshConflicts;
        protected global::System.Web.UI.WebControls.GridView gvConflicts;
    }
}
