//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerSQL.Tools
{
    public partial class XMLtoSQL
    {
        protected global::System.Web.UI.ScriptManager smXmlToSql;
        protected global::System.Web.UI.UpdateProgress upgXmlToSql;
        protected global::System.Web.UI.UpdatePanel upnlXmlToSql;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.LinkButton btnTabXml;
        protected global::System.Web.UI.WebControls.LinkButton btnTabManual;
        protected global::System.Web.UI.WebControls.MultiView mvModes;
        protected global::System.Web.UI.WebControls.View viewXml;
        protected global::System.Web.UI.WebControls.TextBox FileNameTextBox;
        protected global::System.Web.UI.WebControls.Button RefreshFilesButton;
        protected global::System.Web.UI.WebControls.Button GoButton;
        protected global::System.Web.UI.WebControls.ImageButton btnBack;
        protected global::System.Web.UI.WebControls.Panel pnlFileBrowser;
        protected global::System.Web.UI.WebControls.Literal ltrlFileList;
        protected global::System.Web.UI.WebControls.View viewManual;
        protected global::System.Web.UI.WebControls.TextBox tbxManualSql;
        protected global::System.Web.UI.WebControls.DropDownList ddlManualType;
        protected global::System.Web.UI.WebControls.Button btnManualExecute;
        protected global::System.Web.UI.WebControls.Button btnManualClear;
        protected global::System.Web.UI.WebControls.ImageButton btnBackManual;
        protected global::System.Web.UI.WebControls.GridView gvManualHistory;
        protected global::System.Web.UI.WebControls.GridView gvSQLResults;
        protected global::System.Web.UI.WebControls.Panel pnlSQLResults;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlStatus;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
    }
}
